### ISSUE TITLE
Handle Jason errors for malformed requests

### ISSUE THREAD

**Issue by giusdp** [funlessdev/funless-core#36]
I noticed that if Jason encounters something it can't parse, the core crashes cause. It should be handled
with a proper reply for the user. 

For example send an invoke request with some error in the body, for instance:

```
{ function: hello, }
```

The core should send back a reply with status 400 (Bad Request) with a json:
```
{"error":"Failed to parse json in request. Malformed body."}
``` 

This issue is related to #27 but goes more in depth for the json de/encoding scenario.

**Comment by mattrent** [comment]
Closed with #47
